neoforge_version=21.9.16-beta
packs=hud-render-matrix,project-camera-classic,owner-reference,key-category-location,options-list-legacy,screen-field,keybinds-options,world-flags,input-event,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=1.21.9-1.21.10
mc_range=[1.21.9,1.21.11)
neoforge_range=[21.9,21.11)
java=21
