neoforge_version=21.8.54
packs=hud-render-matrix,project-camera-classic,owner-reference,key-category-string,options-list-legacy,screen-field,keybinds-options,world-flags,input-legacy,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=1.21.8
mc_range=[1.21.8]
neoforge_range=[21.8,21.9)
java=21
