neoforge_version=21.0.167
packs=hud-render-pose,project-camera-oldpos64,owner-uuid,key-category-string,options-list-legacy,screen-field,keybinds-options,world-rules,input-legacy,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=1.21-1.21.1
mc_range=[1.21,1.21.2)
neoforge_range=[21.0,21.2)
java=21
