neoforge_version=21.11.45
packs=hud-render-matrix,project-camera-classic,owner-reference,key-category-identifier,options-list,screen-field,keybinds-options,world-gamerules,input-event,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=1.21.11
mc_range=[1.21.11]
neoforge_range=[21.11,)
java=21
