neoforge_version=21.6.20-beta
packs=hud-render-matrix,project-camera-classic,owner-reference,key-category-string,options-list-legacy,screen-field,keybinds-options,world-flags,input-legacy,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=1.21.6-1.21.8
mc_range=[1.21.6,1.21.9)
neoforge_range=[21.6,21.9)
java=21
