neoforge_version=26.1.2.109
packs=hud-extract-gui,project-camera-legacy,owner-reference,key-category-identifier,options-list,screen-field,keybinds-options,world-difficulty,input-event,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=26.1.2
mc_range=[26.1.2]
neoforge_range=[26.1.2,26.2)
java=25
