neoforge_version=26.3.0.8-beta
packs=hud-extract,project-camera,owner-reference,key-category-identifier,options-list,screen-gui,keybinds-options,world-difficulty,input-event,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=26.3
mc_range=[26.3,26.4)
neoforge_range=[26.3,26.4)
java=25
