fabric_api_version=0.77.0+1.18.2
modmenu_version=3.2.5
packs=hud-render-1192,project-camera-118,owner-uuid,keys-binding,key-category-string,options-grid-1192,screen-field,keybinds-controls,world-118,input-1192,attack-damage-legacy,ground-legacy,text-components-118,server-118,registry-legacy,focus-legacy
label=1.18.2
range=>=1.18.2 <1.19
java=17
