fabric_api_version=0.77.0+1.19.2
modmenu_version=4.1.2
packs=hud-render-1192,project-camera-1192,owner-uuid,keys-binding,key-category-string,options-grid-1192,screen-field,keybinds-controls,world-1192,input-1192,attack-damage-legacy,ground-legacy,text-components,server-119,registry-legacy,focus-legacy
label=1.19.2
range=>=1.19.2 <1.19.3
java=17
