fabric_api_version=0.97.3+1.20.4
modmenu_version=9.2.0
packs=hud-render-float,project-camera-euler,owner-uuid,keys-binding,key-category-string,options-grid,screen-field,keybinds-controls,world-rules,input-legacy,attack-damage-legacy,ground,text-components,server-119,registry-builtin,focus
label=1.20.2-1.20.4
range=>=1.20.2 <1.20.5
java=17
