fabric_api_version=0.92.6+1.20.1
modmenu_version=7.2.2
packs=hud-render-float,project-camera-euler,owner-uuid,keys-binding,key-category-string,options-grid-legacy,screen-field,keybinds-controls,world-legacy,input-legacy,attack-damage-legacy,ground,text-components,server-119,registry-builtin,focus
label=1.20-1.20.1
range=>=1.20 <1.20.2
java=17
