fabric_api_version=0.106.1+1.21.2
modmenu_version=12.0.1
packs=hud-render-pose,project-camera-oldpos,owner-uuid,keys-binding,key-category-string,options-list-legacy,screen-field,keybinds-options,world-flags,input-legacy,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=1.21.2-1.21.4
range=>=1.21.2 <1.21.5
java=21
