fabric_api_version=0.128.2+1.21.6
modmenu_version=15.0.2
packs=hud-render-matrix,project-camera-classic,owner-reference,keys-binding,key-category-string,options-list-legacy,screen-field,keybinds-options,world-flags,input-legacy,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=1.21.6-1.21.8
range=>=1.21.6 <1.21.9
java=21
