fabric_api_version=0.141.6+1.21.11
modmenu_version=17.0.0
packs=hud-render-matrix,project-camera-classic,owner-reference,keys-binding,key-category-identifier,options-list,screen-field,keybinds-options,world-gamerules,input-event,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=1.21.11
range=1.21.11
java=21
