fabric_api_version=0.155.3+26.1.2
modmenu_version=18.0.1
packs=hud-extract-gui,project-camera-legacy,owner-reference,keys-mapping,key-category-identifier,options-list,screen-field,keybinds-options,world-difficulty,input-event,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=26.1-26.1.2
range=>=26.1 <26.2
java=25
