fabric_api_version=0.155.2+26.2
modmenu_version=20.0.1
packs=hud-extract,project-camera,owner-reference,keys-mapping,key-category-identifier,options-list,screen-gui,keybinds-options,world-difficulty,input-event,attack-damage,ground,text-components,server-119,registry-builtin,focus
label=26.2
range=>=26.2 <26.3
java=25
