forge_version=1.16.5-36.2.42
packs=hud-render-1192,project-camera-116,owner-116,key-category-string,options-grid-116,screen-field,keybinds-116,world-116,input-1192,attack-damage-legacy,ground-116,text-components-118,server-116,forge-client-116,registry-legacy,focus-legacy
label=1.16.5
java=8
mc_range=[1.16.5,1.17)
forge_range=[36,)
loader_range=[36,)
pack_format=6
