forge_version=1.19.2-43.5.2
mixinextras_version=0.5.5
packs=hud-render-1192,project-camera-1192,owner-uuid,key-category-string,options-grid-1192,screen-field,keybinds-controls,world-1192,input-1192,attack-damage-legacy,ground-legacy,text-components,server-119,forge-client,registry-legacy,focus-legacy
label=1.19.2
java=17
mc_range=[1.19.2,1.19.3)
forge_range=[43,)
loader_range=[43,)
pack_format=9
