forge_version=1.20.1-47.4.23
mixinextras_version=0.5.5
packs=hud-render-float,project-camera-euler,owner-uuid,key-category-string,options-grid-legacy,screen-field,keybinds-controls,world-legacy,input-legacy,attack-damage-legacy,ground,text-components,server-119,forge-client,registry-builtin,focus
label=1.20.1
java=17
mc_range=[1.20.1,1.20.2)
forge_range=[47,)
loader_range=[47,)
pack_format=15
